version: '3.2'

services:

  container_b:
    image: gitlab/gitlab-ee:latest
    container_name: container_b
    restart: always

  container_a:
    image: docker:tester
    container_name: container_a
    command: ["/my_wrapper_script.sh"]
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/log:/tmp/log
